### PR TITLE
ViewCommand, ListCommand

### PR DESCRIPTION
**Pull request by SendorasLeft**
Added ViewCommand and updated ListCommand implementation respectively

### CODE REVIEW

**Comment by cheongliyuan** [comment]
merged chensu's PR, theres a conflict now

**Comment by SendorasLeft** [comment]
okay, it should have been fixed now

**Comment by chensu2436** [comment]
mams.json file changed, not sure it's ok or not

**Comment by SendorasLeft** [comment]
if it matters, the mams.json file changes was from one of the upstream PR commits from another person that I merged before making this PR. my own changes to the json were unstaged before each commit. wasn't too sure whether they were significant so I let them be

**Pull request merged**
