### PR TITLE
Undo + overload commands to prep undo

### PR DESCRIPTION
**Pull request by MistyRainforest**

### CODE REVIEW

**Comment by MistyRainforest** [comment]
public class DataConversionException extends Exception {
    public DataConversionException(Exception cause) {
        super(cause);
    }

}
There is literally no other way to do this that suits Coadacy

**Comment by AaronLuk** [comment]
LGTM

**Comment by MistyRainforest** [comment]
> 
> 
> LGTM

Approve helpz

**Comment by AaronLuk** [comment]
So just ignore the codacy and merge?

**Pull request merged**
